graph LR;
    A[First Visual,<br> Select Subset of Data]-->B[Selection of Data<br> from Visual];
    B-->D[Second Visual with<br> Selected Data ONLY];
    B-->E[Third Visual with<br> Selected Data ONLY];
    B-->F[Fourth Visual with<br> Selected Data ONLY];